[project]
name = "price-table"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "numpy-financial>=1.0.0",
    "numpy>=2.4.0",
    "pandas>=2.3.3",
    "streamlit>=1.52.2",
]
